// @generated by protoc-gen-connect-es v0.13.2
// @generated from file cloud/agent/v1/agent.proto (package cloud.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AskAgentRequest, AskAgentResponse, CreateGlossaryRequest, CreateGlossaryResponse, DeployAgentRequest, DeployAgentResponse, DestroyAgentRequest, DestroyAgentResponse, HistoryAgentRequest, HistoryAgentResponse, ListAgentRequest, ListAgentResponse, ListGlossaryRequest, ListGlossaryResponse, QueryAgentRequest, QueryAgentResponse, RegisterAgentRequest, RegisterAgentResponse } from "./agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Agent service definition
 *
 * @generated from service cloud.agent.v1.AgentService
 */
export const AgentService = {
  typeName: "cloud.agent.v1.AgentService",
  methods: {
    /**
     * API call for registering the agent with the control plane.
     *
     * @generated from rpc cloud.agent.v1.AgentService.Register
     */
    register: {
      name: "Register",
      I: RegisterAgentRequest,
      O: RegisterAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * API call will return list of agent
     *
     * @generated from rpc cloud.agent.v1.AgentService.List
     */
    list: {
      name: "List",
      I: ListAgentRequest,
      O: ListAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * API call will return history of agent
     *
     * @generated from rpc cloud.agent.v1.AgentService.Ask
     */
    ask: {
      name: "Ask",
      I: AskAgentRequest,
      O: AskAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * API call will return history of agent
     *
     * @generated from rpc cloud.agent.v1.AgentService.CreateGlossary
     */
    createGlossary: {
      name: "CreateGlossary",
      I: CreateGlossaryRequest,
      O: CreateGlossaryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * API call will return history of agent
     *
     * @generated from rpc cloud.agent.v1.AgentService.ListGlossary
     */
    listGlossary: {
      name: "ListGlossary",
      I: ListGlossaryRequest,
      O: ListGlossaryResponse,
      kind: MethodKind.Unary,
    },
    /**
     * API call will return deployment of agent
     *
     * @generated from rpc cloud.agent.v1.AgentService.Deploy
     */
    deploy: {
      name: "Deploy",
      I: DeployAgentRequest,
      O: DeployAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc cloud.agent.v1.AgentService.Destroy
     */
    destroy: {
      name: "Destroy",
      I: DestroyAgentRequest,
      O: DestroyAgentResponse,
      kind: MethodKind.Unary,
    },
  }
};

/**
 * Agent service definition
 *
 * @generated from service cloud.agent.v1.SearchService
 */
export const SearchService = {
  typeName: "cloud.agent.v1.SearchService",
  methods: {
    /**
     * API call will return history of agent
     *
     * @generated from rpc cloud.agent.v1.SearchService.Query
     */
    query: {
      name: "Query",
      I: QueryAgentRequest,
      O: QueryAgentResponse,
      kind: MethodKind.Unary,
    },
  }
};

/**
 * Agent service definition
 *
 * @generated from service cloud.agent.v1.HistoryService
 */
export const HistoryService = {
  typeName: "cloud.agent.v1.HistoryService",
  methods: {
    /**
     * API call will return history of agent
     *
     * @generated from rpc cloud.agent.v1.HistoryService.History
     */
    history: {
      name: "History",
      I: HistoryAgentRequest,
      O: HistoryAgentResponse,
      kind: MethodKind.Unary,
    },
  }
};

