apiVersion: v1
kind: Secret
metadata:
  name: { { include "sherlock.fullname" . } }
  labels: { { - include "sherlock.labels" . | nindent 4 } }
type: Opaque
stringData:
  tunnel_token: { { .Values.tunnelToken } }
  password: { { .Values.password } }
  api_key: { { .Values.apiKey } }
  client_secret: { { .Values.clientSecret } }
