// @generated by protoc-gen-connect-es v0.13.2
// @generated from file client/agent/v1/agent.proto (package client.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AskAgentRequest, AskAgentResponse, HeartbeatRequest, HeartbeatResponse } from "./agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Agent service definition
 *
 * @generated from service client.agent.v1.AgentService
 */
export declare const AgentService: {
  readonly typeName: "client.agent.v1.AgentService",
  readonly methods: {
    /**
     * API call will return history of agent
     *
     * @generated from rpc client.agent.v1.AgentService.Ask
     */
    readonly ask: {
      readonly name: "Ask",
      readonly I: typeof AskAgentRequest,
      readonly O: typeof AskAgentResponse,
      readonly kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc client.agent.v1.AgentService.Heartbeat
     */
    readonly heartbeat: {
      readonly name: "Heartbeat",
      readonly I: typeof HeartbeatRequest,
      readonly O: typeof HeartbeatResponse,
      readonly kind: MethodKind.Unary,
    },
  }
};

