// @generated by protoc-gen-connect-es v0.13.2
// @generated from file client/agent/v1/agent.proto (package client.agent.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AskAgentRequest, AskAgentResponse, HeartbeatRequest, HeartbeatResponse } from "./agent_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Agent service definition
 *
 * @generated from service client.agent.v1.AgentService
 */
export const AgentService = {
  typeName: "client.agent.v1.AgentService",
  methods: {
    /**
     * API call will return history of agent
     *
     * @generated from rpc client.agent.v1.AgentService.Ask
     */
    ask: {
      name: "Ask",
      I: AskAgentRequest,
      O: AskAgentResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc client.agent.v1.AgentService.Heartbeat
     */
    heartbeat: {
      name: "Heartbeat",
      I: HeartbeatRequest,
      O: HeartbeatResponse,
      kind: MethodKind.Unary,
    },
  }
};

