# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from datasherlock.cloud.agent.v1 import agent_pb2 as cloud_dot_agent_dot_v1_dot_agent__pb2


class AgentServiceStub(object):
    """Agent service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/cloud.agent.v1.AgentService/Register',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/cloud.agent.v1.AgentService/List',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentResponse.FromString,
                )
        self.History = channel.unary_unary(
                '/cloud.agent.v1.AgentService/History',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentResponse.FromString,
                )
        self.Ask = channel.unary_unary(
                '/cloud.agent.v1.AgentService/Ask',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.FromString,
                )
        self.Health = channel.unary_unary(
                '/cloud.agent.v1.AgentService/Health',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentResponse.FromString,
                )
        self.Query = channel.unary_unary(
                '/cloud.agent.v1.AgentService/Query',
                request_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentRequest.SerializeToString,
                response_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentResponse.FromString,
                )


class AgentServiceServicer(object):
    """Agent service definition
    """

    def Register(self, request, context):
        """API call for registering the agent with the control plane.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """API call will return list of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def History(self, request, context):
        """API call will return history of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ask(self, request, context):
        """API call will return history of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """API call will return history of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Query(self, request, context):
        """API call will return history of agent
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentResponse.SerializeToString,
            ),
            'History': grpc.unary_unary_rpc_method_handler(
                    servicer.History,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentResponse.SerializeToString,
            ),
            'Ask': grpc.unary_unary_rpc_method_handler(
                    servicer.Ask,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentResponse.SerializeToString,
            ),
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentRequest.FromString,
                    response_serializer=cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cloud.agent.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """Agent service definition
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/Register',
            cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.RegisterAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/List',
            cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.ListAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def History(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/History',
            cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.HistoryAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Ask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/Ask',
            cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.AskAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/Health',
            cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.HealthAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cloud.agent.v1.AgentService/Query',
            cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentRequest.SerializeToString,
            cloud_dot_agent_dot_v1_dot_agent__pb2.QueryAgentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
